MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./hello-world/build
	$(QUIET)$(MAKE) -C ./variables/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-1/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-2/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-3/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-4/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-5/build
	$(QUIET)$(MAKE) -C ./loops/for/ex-6/build
clean:
	$(QUIET)$(CLEAN) -C ./hello-world/build
	$(QUIET)$(CLEAN) -C ./variables/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-1/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-2/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-3/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-4/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-5/build
	$(QUIET)$(CLEAN) -C ./loops/for/ex-6/build
